//$file${./Source::TLmain.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: TrafficLight.qm
// File:  ${./Source::TLmain.c}
//
// This code has been generated by QM 6.2.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// Copyright (c) 2005 Quantum Leaps, LLC
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for licensees
// interested in retaining the proprietary status of the generated code.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${./Source::TLmain.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"
#include "trafficlight.h"
#include "bsp.h"

/* "fudge factor" for Windows, see NOTE1 */
enum { WIN_FUDGE_FACTOR = WIN_FUDGE };

Q_DEFINE_THIS_FILE

//$declare${AOs::Ticker_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Ticker_ctor} ........................................................
static void Ticker_ctor(void);
//$enddecl${AOs::Ticker_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$declare${AOs::callConstructors} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::callConstructors} ...................................................
static void callConstructors(void);
//$enddecl${AOs::callConstructors} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$declare${AOs::startAllActiveObjects} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::startAllActiveObjects} ..............................................
static void startAllActiveObjects(void);
//$enddecl${AOs::startAllActiveObjects} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/* AO event queues & event pool data storage */
static QEvt const *trafficQueueStoA[5 * WIN_FUDGE_FACTOR];
static QEvt const *trafficQueueStoB[5 * WIN_FUDGE_FACTOR];
static QEvt const *pedestrianQueueSto[5 * WIN_FUDGE_FACTOR];
static QEvt const *blinkerQueueSto[5 * WIN_FUDGE_FACTOR];
static QSubscrList subscrSto[MAX_PUBLISH_SIG];
static QF_MPOOL_EL(QEvt) smlPoolSto[10 * WIN_FUDGE_FACTOR];

/*..........................................................................*/

int tlMain(int argc, char *argv[])
{
    /* object dictionaries... */
    QS_OBJ_DICTIONARY(smlPoolSto);
    QS_OBJ_DICTIONARY(pedestrianQueueSto);
    QS_OBJ_DICTIONARY(trafficQueueStoA);
    QS_OBJ_DICTIONARY(trafficQueueStoB);
    QS_OBJ_DICTIONARY(blinkerQueueSto);

    QS_SIG_DICTIONARY(TIME_TICK_SIG, (void *)0);
    QS_SIG_DICTIONARY(GLOBAL_START_SIG, (void *)0);
    QS_SIG_DICTIONARY(STARTNEWCYCLE_SIG, (void *)0);
    QS_SIG_DICTIONARY(PEDREQUEST_SIG, (void *)0);
    QS_SIG_DICTIONARY(TL_IS_RED_SIG, (void *)0);
    QS_SIG_DICTIONARY(PL_IS_RED_SIG, (void *)0);
    QS_SIG_DICTIONARY(BUTTON_SIG, (void *)0);
    QS_SIG_DICTIONARY(START_BLINK_SIG, (void *)0);
    QS_SIG_DICTIONARY(STOP_BLINK_SIG, (void *)0);
    QS_SIG_DICTIONARY(OFF_BLINK_SIG, (void *)0);
    QS_SIG_DICTIONARY(EMERGENCY_SIG, (void *)0);
    QS_SIG_DICTIONARY(EM_RELEASE_SIG, (void *)0);
    QS_SIG_DICTIONARY(TIMEOUT_SIG, (void *)0);

    /* initialize HW, QPC Framework QF & BSP */
    BSP_HW_init();
    QF_init();
    BSP_init(argc, argv);

#if defined Q_UTEST
    // pause execution of the test and wait for the test script to continue
    QS_TEST_PAUSE();
#endif

    /* initialize publish-subscribe... */
    QF_psInit(subscrSto, Q_DIM(subscrSto));

    /* initialize event pools... */
    QF_poolInit(smlPoolSto, sizeof(smlPoolSto), sizeof(smlPoolSto[0]));

    /* call all AO constructors */
    callConstructors();

    /* start all AOs */
    startAllActiveObjects();

    return QF_run(); /* run the QF application */
}

/* the ticker */
//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::l_ticker0} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::l_ticker0} ..........................................................
static QTicker l_ticker0;
//$enddef${AOs::l_ticker0} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::the_Ticker0} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::the_Ticker0} ........................................................
QActive * const the_Ticker0  = (QActive * const)&l_ticker0.super;
//$enddef${AOs::the_Ticker0} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${AOs::Ticker_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Ticker_ctor} ........................................................
static void Ticker_ctor(void) {
    QS_OBJ_DICTIONARY(the_Ticker0);

    QTicker_ctor(&l_ticker0, 0U); /* ticker AO for tick rate 0 */
}
//$enddef${AOs::Ticker_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/* call all constructors */
//$define${AOs::callConstructors} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::callConstructors} ...................................................
static void callConstructors(void) {
    Ticker_ctor();
    TLtraffic_ctor(); /* instantiate all Philosopher active objects */
    TLpedestrian_ctor(); /* instantiate the Table active object */
    TLblinker_ctor();
}
//$enddef${AOs::callConstructors} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/* start all AOs */
//$define${AOs::startAllActiveObjects} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::startAllActiveObjects} ..............................................
static void startAllActiveObjects(void) {
    uint_fast8_t aoPrio = 1u;

    QACTIVE_START(the_Ticker0, aoPrio++, 0, 0, 0, 0, 0);

    /* start the active objects... */
    QACTIVE_START(AO_TLtrafficA,           /* AO to start */
                  aoPrio++, /* QP priority of the AO */
                  trafficQueueStoA,      /* event queue storage */
                  Q_DIM(trafficQueueStoA), /* queue length [events] */
                  (void *)0,             /* stack storage (not used) */
                  0U,                    /* size of the stack [bytes] */
                 (QEvt *)0);             /* initialization event */

    QACTIVE_START(AO_TLtrafficB,           /* AO to start */
                  aoPrio++, /* QP priority of the AO */
                  trafficQueueStoB,      /* event queue storage */
                  Q_DIM(trafficQueueStoB), /* queue length [events] */
                  (void *)0,             /* stack storage (not used) */
                  0U,                    /* size of the stack [bytes] */
                 (QEvt *)0);             /* initialization event */

    QACTIVE_START(AO_TLpedestrian,                  /* AO to start */
                  aoPrio++, /* QP priority of the AO */
                  pedestrianQueueSto,             /* event queue storage */
                  Q_DIM(pedestrianQueueSto),      /* queue length [events] */
                  (void *)0,                 /* stack storage (not used) */
                  0U,                        /* size of the stack [bytes] */
                  (QEvt *)0);                /* initialization event */

    QACTIVE_START(AO_TLblinker,                  /* AO to start */
                  aoPrio++, /* QP priority of the AO */
                  blinkerQueueSto,             /* event queue storage */
                  Q_DIM(blinkerQueueSto),      /* queue length [events] */
                  (void *)0,                 /* stack storage (not used) */
                  0U,                        /* size of the stack [bytes] */
                  (QEvt *)0);                /* initialization event */
}
//$enddef${AOs::startAllActiveObjects} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

/*****************************************************************************
* NOTE1:
* Windows is not a deterministic real-time system, which means that the
* system can occasionally and unexpectedly "choke and freeze" for a number
* of seconds. The designers of Windows have dealt with these sort of issues
* by massively oversizing the resources available to the applications. For
* example, the default Windows GUI message queues size is 10,000 entries,
* which can dynamically grow to an even larger number. Also the stacks of
* Win32 threads can dynamically grow to several megabytes.
*
* In contrast, the event queues, event pools, and stack size inside the
* real-time embedded (RTE) systems can be (and must be) much smaller,
* because you typically can put an upper bound on the real-time behavior
* and the resulting delays.
*
* To be able to run the unmodified applications designed originally for
* RTE systems on Windows, and to reduce the odds of resource shortages in
* this case, the generous WIN_FUDGE_FACTOR is used to oversize the
* event queues and event pools.
*/
