/*$file${./Source::bsp.h} ##################################################*/
/*
* Model: TrafficLight.qm
* File:  /home/stefan/Projects/TrafficLight/Source/bsp.h
*
* This code has been generated by QM tool (https://state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*$endhead${./Source::bsp.h} ###############################################*/
#ifndef bsp_gui_h
#define bsp_gui_h

#if defined(QWIN_GUI) && defined(__WIN32__) && (! defined(USE_GTK))
int     main_gui(void);
#else
int     main_gui(int argc, char *argv[]);
#endif
int startGui(int argc, char *argv[]);

void guiSetLight(eTLidentity_t id, uint8_t light);
void guiSetPedLed(uint16_t status);
void guiAssert(char const * const module, int_t loc);
void guiTerminate(int16_t result);
uint16_t guiGetButton(void);

#endif /* bsp_gui_h */
