/*.$file${../BSP::bsp.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: TrafficLight.qm
* File:  ${../BSP::bsp.h}
*
* This code has been generated by QM 5.1.3 <www.state-machine.com/qm/>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*.$endhead${../BSP::bsp.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#ifndef bsp_h
#define bsp_h

#define BSP_TICKS_PER_SEC    1000U

void BSP_HW_init(void);
void BSP_init(int argc, char *argv[]);
void BSP_terminate(int16_t result);

void BSP_setlight(eTLidentity_t id, uint8_t light);
void BSP_setPedLed(uint16_t status);
void BSP_publishBtnEvt(void);
void BSP_publishEmergencyEvt(void);

/* "Ticker" active object for tick rate 0 */
/*.$declare${AOs::the_Ticker0} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
extern QActive * const the_Ticker0;
/*.$enddecl${AOs::the_Ticker0} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

#endif /* bsp_h */