#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDB_TL_LEDRED                           103
#define IDB_TL_LEDWHITE                         109
#define IDB_DISPLAY                             111
#define IDB_SEG0                                200
#define IDB_SEG1                                201
#define IDB_SEG2                                202
#define IDB_SEG3                                203
#define IDB_SEG4                                204
#define IDB_SEG5                                205
#define IDB_SEG6                                206
#define IDB_SEG7                                207
#define IDB_SEG8                                208
#define IDB_SEG9                                209
#define IDB_BTN_UP								301
#define IDB_BTN_DWN								302
#define IDD_APPLICATION                         1000
#define IDB_TL_RED                              1100
#define IDB_TL_YELLOW                           1200
#define IDB_TL_GREEN                            1300
#define IDB_TL_OFF                              1400
#define IDC_RED_A                               2000
#define IDC_YELLOW_A                            2100
#define IDC_GREEN_A                             2200
#define IDC_RED_B                               3000
#define IDC_YELLOW_B                            3100
#define IDC_GREEN_B                             3200
#define IDC_RED_P                               4000
#define IDC_GREEN_P                             4100
#define IDC_TL_A                                5000
#define IDC_TL_B                                5001
#define IDC_TL_PED                              5002
#define IDC_PED_BTN                             5003
#define IDC_EMRG_BTN                            5004
#define IDC_LED_PED                             5005
#define IDC_DIGIT3                              40000
#define IDC_DIGIT2                              40001
#define IDC_DIGIT1                              40002
