/*$file${./Source::bsp.h} ##################################################*/
/*
* Model: TrafficLight.qm
* File:  /home/stenny/Projects/TrafficLight/Source/bsp.h
*
* This code has been generated by QM tool (https://state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*$endhead${./Source::bsp.h} ###############################################*/
#ifndef bsp_h
#define bsp_h

#define BSP_TICKS_PER_SEC    100U

void BSP_init(int argc, char *argv[]);
void BSP_terminate(int16_t result);

void BSP_setlight(eTLidentity_t id, eTLlight_t light);
void BSP_setPedLed(uint16_t status);
// uint16_t BSP_getButton(void);

extern QActive *the_Ticker0; /* "Ticker" active object for tick rate 0 */

#endif /* bsp_h */
