/*$file${./Source::TLbutton.c} #############################################*/
/*
* Model: TrafficLight.qm
* File:  ${./Source::TLbutton.c}
*
* This code has been generated by QM tool (https://state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*$endhead${./Source::TLbutton.c} ##########################################*/
#include "qpc.h"
#include "trafficlight.h"
#include "bsp.h"

Q_DEFINE_THIS_FILE

/* Active object class -----------------------------------------------------*/
/*$declare${AOs::TLbutton} #################################################*/
/*${AOs::TLbutton} .........................................................*/
typedef struct {
/* protected: */
    QActive super;

/* private: */
    QTimeEvt timeEvt;
} TLbutton;

/* protected: */
static QState TLbutton_initial(TLbutton * const me, QEvt const * const e);
static QState TLbutton_RUN(TLbutton * const me, QEvt const * const e);
/*$enddecl${AOs::TLbutton} #################################################*/

/* Local objects -----------------------------------------------------------*/
static TLbutton l_button;   /* storage for PL */

/* Global objects ----------------------------------------------------------*/
QActive * const AO_TLbutton = &l_button.super;   /* "opaque" pointer to PL AO */

/* PL definition --------------------------------------------------------*/
/*$define${AOs::TLbutton_ctor} #############################################*/
/* Check for the minimum required QP version */
#if ((QP_VERSION < 601) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8)))
#error qpc version 6.0.1 or higher required
#endif
/*${AOs::TLbutton_ctor} ....................................................*/
void TLbutton_ctor(void) {
    TLbutton *me = &l_button;

    QActive_ctor(&me->super, Q_STATE_CAST(&TLbutton_initial));
    QTimeEvt_ctorX(&me->timeEvt, &me->super, TIMEOUT_SIG, 0U);
}
/*$enddef${AOs::TLbutton_ctor} #############################################*/
/*$define${AOs::TLbutton} ##################################################*/
/*${AOs::TLbutton} .........................................................*/
/*${AOs::TLbutton::SM} .....................................................*/
static QState TLbutton_initial(TLbutton * const me, QEvt const * const e) {
    /*${AOs::TLbutton::SM::initial} */
    return Q_TRAN(&TLbutton_RUN);
}
/*${AOs::TLbutton::SM::RUN} ................................................*/
static QState TLbutton_RUN(TLbutton * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::TLbutton::SM::RUN} */
        case Q_ENTRY_SIG: {
            QTimeEvt_armX(&me->timeEvt, T_5ms, T_5ms);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::TLbutton::SM::RUN::TIMEOUT} */
        case TIMEOUT_SIG: {
            static QEvt const buttonEvt = { BUTTON_SIG, 0U, 0U };

            if (0 != BSP_getButton())
            {
                QF_PUBLISH(&buttonEvt, me); /* publish to all subscribers */
            }
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*$enddef${AOs::TLbutton} ##################################################*/
